// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VokabelTrainer.Services;

#nullable disable

namespace VokabelTrainer.Model.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20231119181724_AddTrainingItems")]
    partial class AddTrainingItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("VokabelTrainer.Model.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("VokabelTrainer.Model.TrainingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_TrainingRun")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Word")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_TrainingRun");

                    b.HasIndex("Id_Word");

                    b.ToTable("TrainingItems");
                });

            modelBuilder.Entity("VokabelTrainer.Model.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Lesson")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Lesson");

                    b.ToTable("TrainingRuns");
                });

            modelBuilder.Entity("VokabelTrainer.Model.WordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForeignWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Lesson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Lesson");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VokabelTrainer.Model.TrainingItem", b =>
                {
                    b.HasOne("VokabelTrainer.Model.TrainingRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("Id_TrainingRun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VokabelTrainer.Model.WordItem", "Word")
                        .WithMany()
                        .HasForeignKey("Id_Word")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VokabelTrainer.Model.TrainingRun", b =>
                {
                    b.HasOne("VokabelTrainer.Model.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("Id_Lesson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("VokabelTrainer.Model.WordItem", b =>
                {
                    b.HasOne("VokabelTrainer.Model.Lesson", "Lesson")
                        .WithMany("Words")
                        .HasForeignKey("Id_Lesson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("VokabelTrainer.Model.Lesson", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("VokabelTrainer.Model.TrainingRun", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
